modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/yofred09/justessentials/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="justessentials-logo.png"
authors="Yo_Fred"
displayURL="https://github.com/yofred09/justessentials"
description='''
A modular, server-side administration and utility mod for NeoForge servers.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="SERVER"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="SERVER"

[[dependencies.${mod_id}]]
modId="justvanish"
type="optional"
versionRange="[1.2.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="curios"
type="optional"
versionRange="[9.5.1,)"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="accessories"
type="optional"
versionRange="[1.1.0-beta.51,)"
ordering="AFTER"
side="SERVER"
